/*****************************************************************************
 *
 * SDF (Self-Describing Format) VisIt reader
 * Copyright (c) 2010-2016, SDF Development Team
 *
 * Distributed under the terms of the BSD 3-clause License.
 * See the LICENSE file for details.
 *
 ****************************************************************************/

// ************************************************************************* //
//                             avtSDFOptions.h                              //
// ************************************************************************* //

#ifndef AVT_SDF_OPTIONS_H
#define AVT_SDF_OPTIONS_H

class DBOptionsAttributes;

#include <string>

namespace SDFDBOptions
{
    // Read options
    const char *const SDF_RDOPT_CONVERT_FLOAT =
            "Read double variables as floats to save memory";
    const char *const SDF_RDOPT_RANDOMISE = "Randomise particle data";
    const char *const SDF_RDOPT_BOUNDARY = "Populate boundary variables";
    const char *const SDF_RDOPT_ALLBOUNDARY = "Populate side boundary variables";
    const char *const SDF_RDOPT_OB_BOUNDARY =
            "Populate obstacle boundary variables";
}

// ****************************************************************************
//  Functions: avtSDFOptions
//
//  Purpose:
//      Creates the options for  SDF readers and/or writers.
//
//  Programmer: keith -- generated by xml2avt
//  Creation:   Sun Dec 5 22:37:15 PST 2010
//
// ****************************************************************************

DBOptionsAttributes *GetSDFReadOptions(void);
DBOptionsAttributes *GetSDFWriteOptions(void);


#endif
