/*****************************************************************************
 *
 * SDF (Self-Describing Format) VisIt reader
 * Copyright (c) 2010-2016, SDF Development Team
 *
 * Distributed under the terms of the BSD 3-clause License.
 * See the LICENSE file for details.
 *
 ****************************************************************************/

// ************************************************************************* //
//                             avtSDFOptions.C                              //
// ************************************************************************* //

#include <avtSDFOptions.h>

#include <DBOptionsAttributes.h>

#include <string>

using namespace SDFDBOptions;

// ****************************************************************************
//  Function: GetSDFReadOptions
//
//  Purpose:
//      Creates the options for SDF readers.
//
//  Important Note:
//      The code below sets up empty options.  If your format
//      does not require read options, no modifications are
//      necessary.
//
//  Programmer: keith -- generated by xml2avt
//  Creation:   Sun Dec 5 22:37:15 PST 2010
//
// ****************************************************************************

DBOptionsAttributes *
GetSDFReadOptions(void)
{
    DBOptionsAttributes *rv = new DBOptionsAttributes;
    rv->SetBool(SDF_RDOPT_CONVERT_FLOAT, false);
    rv->SetBool(SDF_RDOPT_RANDOMISE, false);
    rv->SetBool(SDF_RDOPT_BOUNDARY, false);
    rv->SetBool(SDF_RDOPT_ALLBOUNDARY, false);
    rv->SetBool(SDF_RDOPT_OB_BOUNDARY, true);
    return rv;
}


// ****************************************************************************
//  Function: GetSDFWriteOptions
//
//  Purpose:
//      Creates the options for SDF writers.
//
//  Important Note:
//      The code below sets up empty options.  If your format
//      does not require write options, no modifications are
//      necessary.
//
//  Programmer: keith -- generated by xml2avt
//  Creation:   Sun Dec 5 22:37:15 PST 2010
//
// ****************************************************************************

DBOptionsAttributes *
GetSDFWriteOptions(void)
{
    DBOptionsAttributes *rv = new DBOptionsAttributes;
    return rv;
}
